name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get versions data from repo
      run: wget -O maven-metadata.xml https://oss.sonatype.org/service/local/repositories/releases/content/io/antmedia/webrtc/ConferenceCall/maven-metadata.xml       

    - name: Download war File
      run: |
        VERSION=${{ github.ref_name }}
        export VERSION=${VERSION:1}
        wget -O ConferenceCall-${{ github.ref_name }}.war "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=io.antmedia.webrtc&a=ConferenceCall&v=${VERSION}&e=war"
        ls -al

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }} is now available.
          Add release notes here.

    - name: Upload assets
      id: upload_assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/ConferenceCall-${{ github.ref_name }}.war
        asset_name: ConferenceCall-${{ github.ref_name }}.war
        asset_content_type: application/zip
